C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/6,5/
      DATA (SPROP(I,-1,1),I=1,4)/-24,-24,-24,-24/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/4,3/
      DATA (SPROP(I,-2,1),I=1,4)/24,24,24,24/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/-1,-2/
      DATA (SPROP(I,-3,1),I=1,4)/54,54,54,54/
      DATA TPRID(-3,1)/0/
C     Number of configs
      DATA MAPCONFIG(0)/1/
